In [9]:
import pandas as pd

In [10]:
#columns to extract from the simulation csv file (t_in for each zone, t_out, heating/cooling/electr. consumption)

selcted_columns= ['Date/Time',
              'BLOCCO1:ZONA1:Zone Operative Temperature [C](TimeStep:ON)',
              'BLOCCO1:ZONA2:Zone Operative Temperature [C](TimeStep:ON)',
              'BLOCCO1:ZONA3:Zone Operative Temperature [C](TimeStep:ON)',
              'Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep)',
              'DistrictHeating:Facility [J](TimeStep)',
              'DistrictCooling:Facility [J](TimeStep)',
              'Electricity:Facility [J](TimeStep)']

In [11]:
optim_results=pd.read_csv('/home/ict4bd/opt_res.csv',usecols=selcted_columns)

In [12]:
#overall internal temperature
optim_results['avg_T_in'] = optim_results[
                            ['BLOCCO1:ZONA1:Zone Operative Temperature [C](TimeStep:ON)',
                             'BLOCCO1:ZONA2:Zone Operative Temperature [C](TimeStep:ON)',
                             'BLOCCO1:ZONA3:Zone Operative Temperature [C](TimeStep:ON)']].mean(axis=1)
#drop not necessary info
optim_results = optim_results.drop(['BLOCCO1:ZONA1:Zone Operative Temperature [C](TimeStep:ON)',
               'BLOCCO1:ZONA2:Zone Operative Temperature [C](TimeStep:ON)',
               'BLOCCO1:ZONA3:Zone Operative Temperature [C](TimeStep:ON)'], axis = 1)

In [13]:
#by 15 min
optim_results['Electricity:Facility [J](TimeStep)'] /= 3.6e6
optim_results['DistrictHeating:Facility [J](TimeStep)'] /= 3.6e6
optim_results['DistrictCooling:Facility [J](TimeStep)'] /= 3.6e6





optim_results['Power'] = optim_results['DistrictHeating:Facility [J](TimeStep)'] + optim_results['DistrictCooling:Facility [J](TimeStep)'] + optim_results['Electricity:Facility [J](TimeStep)']

optim_results

,Date/Time,Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep),Electricity:Facility [J](TimeStep),DistrictCooling:Facility [J](TimeStep),DistrictHeating:Facility [J](TimeStep),avg_T_in,Power
0,01/01 00:30:00,8.70,0.000000,0.0,0.327841,19.391931,0.327841
1,01/01 01:00:00,9.50,0.000000,0.0,0.316913,19.386191,0.316913
2,01/01 01:30:00,9.35,0.000000,0.0,0.319189,19.386425,0.319189
3,01/01 02:00:00,9.20,0.000000,0.0,0.320630,19.383375,0.320630
4,01/01 02:30:00,9.10,0.000000,0.0,0.321076,19.380739,0.321076
...,...,...,...,...,...,...,...
17515,12/31 22:00:00,10.70,0.085128,0.0,0.262146,19.634991,0.347273
17516,12/31 22:30:00,10.50,0.075052,0.0,0.201690,19.608156,0.276742
17517,12/31 23:00:00,10.30,0.075052,0.0,0.206810,19.591805,0.281862
17518,12/31 23:30:00,10.05,0.000000,0.0,0.257023,19.574309,0.257023
17519,12/31 24:00:00,9.80,0.000000,0.0,0.264366,19.558376,0.264366

In [14]:
#power consumption 
#print(optim_results['Power'].sum(axis=0))

In [15]:
optim_results= optim_results.rename(columns={'Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep)':'T_out',
                                            'DistrictCooling:Facility [J](TimeStep)':'Cooling Power',
                                            'DistrictHeating:Facility [J](TimeStep)': 'Heating Power'})


optim_results= optim_results.drop(['Electricity:Facility [J](TimeStep)'], axis = 1)
optim_results

,Date/Time,T_out,Cooling Power,Heating Power,avg_T_in,Power
0,01/01 00:30:00,8.70,0.0,0.327841,19.391931,0.327841
1,01/01 01:00:00,9.50,0.0,0.316913,19.386191,0.316913
2,01/01 01:30:00,9.35,0.0,0.319189,19.386425,0.319189
3,01/01 02:00:00,9.20,0.0,0.320630,19.383375,0.320630
4,01/01 02:30:00,9.10,0.0,0.321076,19.380739,0.321076
...,...,...,...,...,...,...
17515,12/31 22:00:00,10.70,0.0,0.262146,19.634991,0.347273
17516,12/31 22:30:00,10.50,0.0,0.201690,19.608156,0.276742
17517,12/31 23:00:00,10.30,0.0,0.206810,19.591805,0.281862
17518,12/31 23:30:00,10.05,0.0,0.257023,19.574309,0.257023
17519,12/31 24:00:00,9.80,0.0,0.264366,19.558376,0.264366

In [16]:
optim_results.to_csv(path_or_buf='data_2.csv',index=False)