In [88]:
import pandas as pd

In [89]:
#columns to extract from the simulation csv file (t_in for each zone, t_out, heating/cooling/electr. consumption)

selcted_columns= ['Date/Time',
              'BLOCCO1:ZONA1:Zone Operative Temperature [C](TimeStep:ON)',
              'BLOCCO1:ZONA2:Zone Operative Temperature [C](TimeStep:ON)',
              'BLOCCO1:ZONA3:Zone Operative Temperature [C](TimeStep:ON)',
              'Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep)',
              'DistrictHeating:Facility [J](TimeStep)',
              'DistrictCooling:Facility [J](TimeStep)',
              'Electricity:Facility [J](TimeStep)']

In [90]:
optim_results=pd.read_csv('eplusout_2021.csv',usecols=selcted_columns)

In [91]:
#overall internal temperature
optim_results['avg_T_in'] = optim_results[
                            ['BLOCCO1:ZONA1:Zone Operative Temperature [C](TimeStep:ON)',
                             'BLOCCO1:ZONA2:Zone Operative Temperature [C](TimeStep:ON)',
                             'BLOCCO1:ZONA3:Zone Operative Temperature [C](TimeStep:ON)']].mean(axis=1)
#drop not necessary info
optim_results = optim_results.drop(['BLOCCO1:ZONA1:Zone Operative Temperature [C](TimeStep:ON)',
               'BLOCCO1:ZONA2:Zone Operative Temperature [C](TimeStep:ON)',
               'BLOCCO1:ZONA3:Zone Operative Temperature [C](TimeStep:ON)'], axis = 1)

In [92]:
#kWh
timestep=3.6e6


optim_results['Electricity:Facility [J](TimeStep)'] /= timestep
optim_results['DistrictHeating:Facility [J](TimeStep)'] /= timestep
optim_results['DistrictCooling:Facility [J](TimeStep)'] /= timestep




optim_results['Power'] = optim_results['DistrictHeating:Facility [J](TimeStep)'] + optim_results['DistrictCooling:Facility [J](TimeStep)'] + optim_results['Electricity:Facility [J](TimeStep)']

optim_results

,Date/Time,Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep),Electricity:Facility [J](TimeStep),DistrictCooling:Facility [J](TimeStep),DistrictHeating:Facility [J](TimeStep),avg_T_in,Power
0,01/01 00:10:00,4.537037,0.007091,0.0,0.075816,16.523826,0.082907
1,01/01 00:20:00,4.629630,0.007091,0.0,0.075239,16.512207,0.082330
2,01/01 00:30:00,4.722222,0.007091,0.0,0.074674,16.497383,0.081765
3,01/01 00:40:00,4.814815,0.007091,0.0,0.074119,16.483336,0.081210
4,01/01 00:50:00,4.907407,0.007091,0.0,0.073571,16.471094,0.080663
...,...,...,...,...,...,...,...
52555,12/31 23:20:00,1.481481,0.009633,0.0,0.061057,17.004329,0.070690
52556,12/31 23:30:00,1.388889,0.009633,0.0,0.061207,16.994250,0.070840
52557,12/31 23:40:00,1.296296,0.009633,0.0,0.061371,16.976093,0.071004
52558,12/31 23:50:00,1.203704,0.009633,0.0,0.061546,16.933520,0.071179
52559,12/31 24:00:00,1.111111,0.009633,0.0,0.061733,16.893100,0.071366

In [94]:
#power consumption 
print(optim_results['Power'].sum(axis=0))

14.303726636458673

In [46]:
optim_results= optim_results.rename(columns={'Environment:Site Outdoor Air Drybulb Temperature [C](TimeStep)':'T_out',
                                            'DistrictCooling:Facility [J](TimeStep)':'Cooling Power',
                                            'DistrictHeating:Facility [J](TimeStep)': 'Heating Power'})


optim_results= optim_results.drop(['Electricity:Facility [J](TimeStep)'], axis = 1)
optim_results

,Date/Time,T_out,Cooling Power,Heating Power,avg_T_in,Power
0,01/01 00:10:00,4.537037,0.0,0.454896,16.523826,0.497444
1,01/01 00:20:00,4.629630,0.0,0.451433,16.512207,0.493981
2,01/01 00:30:00,4.722222,0.0,0.448041,16.497383,0.490589
3,01/01 00:40:00,4.814815,0.0,0.444714,16.483336,0.487262
4,01/01 00:50:00,4.907407,0.0,0.441428,16.471094,0.483976
...,...,...,...,...,...,...
52555,12/31 23:20:00,1.481481,0.0,0.366344,17.004329,0.424142
52556,12/31 23:30:00,1.388889,0.0,0.367244,16.994250,0.425043
52557,12/31 23:40:00,1.296296,0.0,0.368225,16.976093,0.426024
52558,12/31 23:50:00,1.203704,0.0,0.369278,16.933520,0.427076
52559,12/31 24:00:00,1.111111,0.0,0.370399,16.893100,0.428198

In [47]:
optim_results.to_csv(path_or_buf='data_2021.csv',index=False)